#
# GNUmakefile - Generated by ProjectCenter
#

include $(GNUSTEP_MAKEFILES)/common.make
include GNUmakefile.preamble

#
# Tool
#
VERSION = 0.1
PACKAGE_NAME = mercury
TOOL_NAME = mercury
mercury_TOOL_ICON = 
GNUSTEP_INSTALLATION_DIR = $(HOME)/

#
# Libraries
#
# libstdc++.a is in a different place on every system.  Find yours and put it here.
# Good starting point: `locate libstdc++.a`

#mercury_TOOL_LIBS += /usr/local/lib64/libstdc++.a
#mercury_TOOL_LIBS += /usr/lib/gcc/x86_64-redhat-linux/4.3.0/32/libstdc++.a

#
# Header files
#
mercury_HEADER_FILES = \
HMHTL.h \
HMStepper.h \
HMInputSplitter.h \
HM2DTVDD.h \
XML\ procedures.h \
HMClock.h \
HMInput.h \
HMLevel.h \
HMNode.h \
HMOutput.h \
HMPart.h \
HMPort.h \
HMTVDD.h \
HMLookup.h \
HMExpression.h \
HMFile.h \
Parsing.h \
Instantiator.h \
Value.h \
y.tab.h \
AppController.h \
Dependency.h

#
# Class files
#
mercury_OBJC_FILES = \
HMStepper.m \
HMInputSplitter.m \
HM2DTVDD.m \
XML_procedures_Linux.m \
HMClock.m \
Hernix.m \
HMInput.m \
HMLevel.m \
HMNode.m \
HMOutput.m \
HMPart.m \
HMPort.m \
HMTVDD.m \
HMHTL.m \
HMLookup.m \
HMFile.m \
Parsing.m \
Instantiator.m \
Value.m \
AppController.m \
Exceptions.m \
Dependency.m \
#
# C files
#
mercury_C_FILES = \
rules.yy.c \
y.tab.c 



#
# Makefiles
#
include $(GNUSTEP_MAKEFILES)/tool.make

